id = "bg3-extension"
name = "Baldurs Gate 3 Modding Extension"
version = "0.0.1"
schema_version = 1
authors = ["Your Name <you@example.com>"]
description = "My cool extension"
repository = "https://github.com/your-name/my-zed-extension"

[language_servers.bg3]
name = "BG3 Modding"
language = "BG3 Modding File"

[grammars.bg_3]
repository = "https://github.com/saeschdivara/zed-bg3/bg3-zed-extension"
commit = "654d13914b906bc7aaac21a98a7b1d80ceb628b2"